def get_text(lang=1, code='', appendix='') :
    texts_data = {
        "en" : {
            "hello" : "Dear",
            "brief_info" : "Information about",
            "thanks" : "Thanks",
            "thanks_return": "Thanks, we hope that you can return later",
            "greeting" : "Thanks you  it is greeting text",
            "consent" : "Do you agree to participate in this experiment?",
            "consent_week" : "Do you agree to participate in this experiment whole week and get notifications?",
            "age" : "How old are you?",
            "gender" : "Your gender?",
            "occupation" : "Your occupation?",
            "region" : "Your region?",
            "ethnicy" : "Type your ethnicy please?",
            "height" : "Type your hieght please?",
            "weight" : "Type your weight please?",
            "is_smoking" : "Are you smoking?",
            "city" : "Your hometown?",
            "yes" : "YES",
            "no" : "NO",
            "sometimes" : "SOMETIMES",
            "gender_man": "Man",
            "gender_other" : "Other",
            "gender_female": "Female",
            "region_south" : "South",
            "region_north" : "North",
            "region_west" : "West",
            "region_east" : "East",
            "region_center" : "Center",
            "occ_other": "Other",
            "oc_legal": "Legal",
            "occ_it": "IT",
            "occ_business": "Business",
            "occ_teaching": "Teaching",
            "occ_health": "Health",
            "occ_science": "Sccience",
            "load_again": "Load again please",
            "load_image_please" : "Please, load image of your meal"
        },
        "ru" : {
            "hello" : "Здравствуйте",
            "brief_info" : "Краткая информация",
            "thanks" : "Спасибо",
            "thanks_return" : "Спасибо, надемся что вы передумаете и согласитесь принять участие в эксперимеенте",
            "greeting" : "Спасибо!",
            "consent" : "Вы согласны принять участие в эскперименте",
            "consent_week": "Вы согласны участовавть в эксперименте целую неделю? ",
            "age" : "Сколько Вам лет?",
            "gender" : "Ваш пол?",
            "occupation" : "Ваша профессия?",
            "region" : "Облость проживания?",
            "ethnicy" : "Национальность?",
            "height" : "Рост?",
            "weight" : "Вес?",
            "is_smoking" : "Вы курите?",
            "city" : "Ваш город или населенный пункт?",
            "yes" : "ДА",
            "no" : "НЕТ",
            "sometimes" : "ИНОГДА",
            "gender_man" : "Мужчина",
            "gender_female" : "Женщина",
            "gender_other" : "Другое",
            "region_south" : "Юг",
            "region_north" : "Север",
            "region_west" : "Запад",
            "region_east" : "Восток",
            "region_center" : "Центр",
            "occ_other" : "Other",
            "oc_legal" : "Legal",
            "occ_it" : "IT",
            "occ_business" : "Business",
            "occ_teaching" : "Teaching",
            "occ_health" : "Health",
            "occ_science" : "Sccience",
            "load_again" :  "Попробуйте еще раз",
            "load_image_please" : "Пожалуйста загрузите фотку еды"
        },
        "kz" : {
            "hello" : "Сәлеметсіз бе",
            "brief_info" : "Қысқаша инфо",
            "thanks": "Рахмет",
            "thanks_return" : "Рахмеет, кейінірек ораларсыз деп сенеміз",
            "greeting" : "тест",
            "consent" : "Экспериментке қатысуға келісесіз бе?",
            "consent_week" : "Экспериментке апта бойы қатысқыңыз келеді ме?",
            "age" : "Жасыңыз?",
            "gender" : "Жынысыңыз?",
            "occupation" : "Жұмысыңыз?",
            "region" : "Облысыңыз?",
            "ethnicy" : "Ұлтыңыз?",
            "height" : "Бойыңыз?",
            "weight" : "Салмағыңыз?",
            "is_smoking" : "Темекі шегесің бе брат?",
            "city" : "Қалаңыз немесе тұрғылықты орныңыз?",
            "yes":  "ЙӘ",
            "no": "ЖОҚ",
            "sometimes" : "КЕЙДЕ",
            "gender_man" : "Ер",
            "gender_female" : "Әйел",
            "gender_other" : "Басқа",
            "region_south" : "Оңтүстің",
            "region_north" : "Солтүстік",
            "region_west" : "Батыс",
            "region_east" : "Шығыс",
            "region_center" : "Орталық",
            "occ_other" : "Other",
            "oc_legal" : "Legal",
            "occ_it" : "IT",
            "occ_business" : "Business",
            "occ_teaching" : "Teaching",
            "occ_health" : "Health",
            "occ_science" : "Sccience",
            "load_again": "Қайта жүктеңіз",
            "load_image_please":  "Өтініш, сурет жүктеңіз"
        }
    }
    result = ''
    try :
        result = texts_data [ lang ] [ code ]
    except :
        result = 'ERROR in TEXT RETRIEVING'

    return result