def get_text(lang=1, code='', appendix=''):
    texts_data = {
        "en": {
            "comment_to_image": "Now, you are ready to start with the experiment. We need you to send images of the food you consume for 5 days (at least 3 weekdays/normal working days).\n Please, take images from top view as shown on sample below.\n\nIf you have questions regarding the project please feel free to contact us: aifoodimage@gmail.com\n\nSource of image: https://www.matain.id/article/10014/2020/1220/5-tips-skill-fotografi-untuk-maksimalkan-bisnis-kuliner-dari-food-blogger.html",
            "hello": "Hello! ",
            "welcome": "Welcome to the Food Image collection Bot.",
            "thanks": "Thank you!",
            "brief_info": 'Here is the informed Consent Form:\n\nYou are invited to participate in a research study entitled:\n\n“AI Applications for Personalised Nutrition Interventions”\n\n' 
                + 'Description: This study aims to collect images of different types of food. This data will be used to build an object detection system, which will recognize food in the image and classify it.\n\n' 
                + 'The data will be collected via Telegram, one of the commonly used cross-platform instant messaging systems. Participants are asked to complete a short 1-minute survey and send photos of their food for five days: ' 
                + '2 weekend days and 3 weekdays. The participants will be reminded to send pictures without any human faces or objects which can be linked back to the respondents.\n\n' 
                + 'Risks: No potential risks are associated with the study.\n\nBenefits: It is unlikely that there will be direct benefits to you from participating in this study; ' 
                + 'however, the study findings may have potentially positive implications to promote effective nutrition apps/platforms for the contribution to a healthy lifestyle among ' 
                + 'the Kazakhstani population.\n\nCompensation: No tangible compensation will be given. A copy of the research results will be available after the study as published papers.\n\n' 
                + 'Confidentiality & Privacy: No personal information which may reveal the identity of the person will be collected. All collected data will be anonymized and stored on the computational ' 
                + ' servers of the Institute of Smart Systems and Artificial Intelligence (ISSAI) and administered only by the investigators of the project. Address: Kabanbay batyr ave 53, Block C4, Office 425.\n\n' 
                + 'Voluntary Nature of the Study. Participation in this study is strictly voluntary, and if the agreement to participate is given, it can be withdrawn at any time without prejudice.\n\n' 
                + 'Points of Contact:\n\nPrincipal Investigator: Dr. Mei-Yen Chan,  yen.chan@nu.edu.kz\n\nCo-Principal Investigator: Dr. Huseyin Atakan Varol  ahvarol@nu.edu.kz\n\n' 
                + 'This study has been reviewed and cleared by the Nazarbayev University Research Ethics Committee.' 
                + 'If you have concerns or questions about your rights as a participant or about the way the study is conducted, you may contact Nazarbayev University Research Ethics Committee. E-mail: resethics@nu.edu.kz',
            "consent": "Do you agree to participate in this experiment?\n\nBy clicking “I agree” below you are indicating that you are at least 18 years old, have read and understood this consent form, and agree to participate in this research study.",
            "thanks_return": "Thank you, we hope that you can return later.",
            "age": "How old are you?",
            "gender": "Your gender?",
            "occupation": "Please, select your occupation\n\n Scroll down the list below to choose from 11 options.",
            "shift_work": "Are your a shift worker?",
            "schedule": "What is your work schedule?",
            "ethnicy": "Please, select your ethnicy",
            "ethnicy_other": "Please, type in your ethnicy",
            "region_kz": "Your location?",
            "region_outside": "Please, type in your city",
            "height": "Type your height in cm, please",
            "weight": "Type your weight in kg, please",
            "waist_circumference": "Please, type in your waist circumference in cm or type 0 if don't know.",
            "is_smoking": "Do you smoke?",
            "ideal_weight": "What is your ideal weight in kg?",
            "breakfast": "When do you typically eat breakfast?",
            "lunch": "When do you typically eat lunch?",
            "dinner": "When do you typically eat dinner?",
            "activity": "How active are you at work?",
            "sleep": "How many hours of sleep do you typically get?",
            "workout": "How often do you work out?",
            "diet": "Has your diet changed after pandemic?",
            "diet_change": "What changes did you make in couple of words",
            "yes": "YES",
            "no": "NO",
            "a_bit": "A little bit",
            "sometimes": "SOMETIMES",
            "gender_man": "Man",
            "gender_other": "Other",
            "gender_female": "Female",
            "ethnicy_1": "Kazakh",
            "ethnicy_2": "Russian",
            "ethnicy_3": "Uzbek",
            "ethnicy_4": "Uyghur",
            "ethnicy_5": "Tatar",
            "ethnicy_6": "Ukranian",
            "ethnicy_7": "Turkish",
            "ethnicy_8": "Azerbaijan",
            "ethnicy_9": "Korean",
            "ethnicy_10": "Other",
            "region_south": "South",
            "region_north": "North",
            "region_west": "West",
            "region_east": "East",
            "region_center": "Center",
            "region_other": "Outside of Kazakhstan",
            "occ_other": "Other",
            "occ_student": "Student",
            "occ_managers": "Managers",
            "occ_professional": "Professional",
            "occ_tech": "Technical and associate professionals",
            "occ_clerical": "Clerical support workers",
            "occ_service": "Service and sales workers",
            "occ_skilled": "Skilled agricultural, forestry, fishery, mining workers",
            "occ_craft": "Craft and related trades workers",
            "occ_operator": "Plant and machine operators, and assemblers",
            "occ_unemployed": "Unemployed",
            "work_9_5": " 9 am to 5 pm",
            "work_flexible": "My hours are flexible",
            "work_hight": "Night shifts",
            "work_no": "I am retired/umeployed/student",
            "breakfast_1": "Between 4 and 6 am",
            "breakfast_2": "Between 6 and 8 am",
            "breakfast_3": "Between 10 and noon",
            "breakfast_4": "I usually skip breakfast",
            "lunch_1": "Between 10 am and noon",
            "lunch_2": "Between noon and 2 pm",
            "lunch_3": "Between 2 pm and  4 pm",
            "lunch_4": "I usually skip lunch",
            "dinner_1": "Between 4 and 6 pm",
            "dinner_2": "Between 6 and 8 pm",
            "dinner_3": "Between 8 and 10 pm",
            "dinner_4": "I usually skip dinner",
            "activity_low": "I mostly sit and do not move much",
            "activity_normal": "I do physical labor work and very active ",
            "activity_mixed": "A mixture of both",
            "sleep_min": "Less than 5 hours",
            "sleep_normal": "5-6 hours",
            "sleep_long": "7-8 hours",
            "sleep_2long": "More than 8 hours",
            "workout_high": "3 to 5 times a week",
            "workout_low": "1 to 2 times a week",
            "workout_very_low": "Less than 1 time per week",
            "load_again": "Load again please",
            "load_image_please": "Please, load image of your meal"
        },
        "ru": {
            "comment_to_image": "Вы можете начать участие в эксперименте. Вам необходимо отправлять фото употребляемой пищи в течении 5 дней(из которых минимум 3 рабочих будней).\n\nEсли у вас есть какие-либо вопросы, пожалуйста, обращайтесь по эл. почте aifoodimage@gmail.com\n\nИсточник изображения: https://www.matain.id/article/10014/2020/1220/5-tips-skill-fotografi-untuk-maksimalkan-bisnis-kuliner-dari-food-blogger.html" 
            + "Пожалуйста, фотографируйте пищу сверху, как показано на примере ниже.",
            "hello": "Здравствуйте! ",
            "welcome": "Добро пожаловать в Бот для сбора изображений еды.",
            "thanks": "Спасибо!",
            "brief_info": 'Форма информированного согласия:\n\nВы приглашены принять участие в исследовании под названием:\n\n“ИИ для персонализированных мероприятий в области питания”\n\nОписание: ' 
                + 'Целью данного исследования является сбор изображений различных видов пищи. Эти данные будут использованы для построения модели обнаружения объектов, ' 
                + 'которая будет распознавать пищу на изображении и классифицировать ее.\n\nДанные будут собираться с помощью Telegram, ' 
                + 'одной из широко используемых кроссплатформенных систем обмена мгновенными сообщениями. Участникам предлагается заполнить короткий 2-минутный опрос ' 
                + 'и отправлять фотографии употребляемой еды в течение пяти дней: 2 выходных дня и 3 рабочих дня. Участники будут получать напоминание в процессе эксперимента. ' 
                + 'Фотографии должны быть без человеческих лиц или предметов, которые могут быть связаны с идентификацей респондента.\n\n' 
                + 'Риски: Потенциальные риски, связанные с исследованием, отсутствуют.\n\nВыгоды: Маловероятно, что вы получите прямую выгоду от участия в данном исследовании; ' 
                + 'однако результаты исследования могут способствовать развитию и  продвижению приложений/платформ по питанию для содействия здоровому образу жизни среди населения Казахстана. ' 
                + '\nКомпенсация: Материальная компенсация за участие отсутствует. Копия результатов исследования будет доступна по завершении в виде опубликованной статьи и базы данных в открытом доступе.\n\n' 
                + 'Конфиденциальность: Никакая личная информация, которая может раскрыть личность человека, собираться не будет. ' 
                + 'Все собранные данные будут анонимизированы и сохранены на вычислительных серверах Института интеллектуальных систем и искусственного интеллекта (ISSAI) и ' 
                + ' будут управляться только исследователями проекта. Адрес: пр. Кабанбай батыра 53, Блок С4, Офис 425.\n\nДобровольный характер исследования. ' 
                + ' Участие в этом исследовании является строго добровольным, и если будет дано согласие на участие, оно может быть приостановлено в любое время.\n\n' 
                + 'Контактные пункты:\n\nГлавный исследователь: Доктор Мэй-Йен Чан, yen.chan@nu.edu.kz\n\nСо-главный исследователь: Доктор Хусейн Атакан Варол, ahvarol@nu.edu.kz\n\n ' 
                + 'Это исследование было рассмотрено и одобрено Комитетом по этике исследований Назарбаев университета. Если у вас есть сомнения или вопросы о ваших правах как участника или о том, ' 
                + ' как проводится исследование, вы можете обратиться в Комитет по этике исследований Назарбаев университета. Электронная почта: resethics@nu.edu.kz',
            "consent": "Вы согласны участвовать в эксперименте? Нажимая “Я согласен” ниже, вы указываете, что вам по крайней мере 18 лет, вы прочитали и поняли эту форму согласия и согласны участвовать в этом исследовании.",
            "thanks_return": "Благодарим, надеюсь вы еще вернетесь.",
            "age": "Введите ваш возраст",
            "gender": "Ваш пол",
            "occupation": "Выберите ваш род занятий\n\nПрокрутите список приведенный ниже для выбора вашего варианта из 11 предоставленных.",
            "shift_work": "У вас сменная работа?",
            "schedule": "Каково ваше рабочее расписание по времени?",
            "ethnicy": "Выберите вашу этническую группу",
            "ethnicy_other": "Введите вашу этническую группу",
            "region_kz": "Где вы проживаете?",
            "region_outside": "Введите название города",
            "height": "Введите ваш рост в см, пожалуйста",
            "weight": "Введите ваш вес в кг, пожалуйста",
            "waist_circumference": "Введите окружность вашей талии в см либо 0, в случае если не знаете",
            "is_smoking": "Вы курите?",
            "ideal_weight": "Ваш идеальный вес в кг?",
            "breakfast": "Когда вы обычно завтракаете?",
            "lunch": "Во сколько вы обычно обедаете?",
            "dinner": "Во сколько вы обычно ужинаете?",
            "activity": "На сколько вы физически активны на работе?",
            "sleep": "Сколько часов обычно вы спите?",
            "workout": "Как часто вы тренируетесь?",
            "diet": "Изменился ли ваш рацион питания после пандемии?",
            "diet_change": "Если да, то опишите кратко изменения",
            "yes": "ДА",
            "no": "НЕТ",
            "a_bit": "Немного",
            "sometimes": "Иногда",
            "gender_man": "Мужчина",
            "gender_female": "Женщина",
            "gender_other": "Другое",
            "ethnicy_1": "Казахи",
            "ethnicy_2": "Русские",
            "ethnicy_3": "Узбеки",
            "ethnicy_4": "Уйгуры",
            "ethnicy_5": "Татары",
            "ethnicy_6": "Украинцы",
            "ethnicy_7": "Турки",
            "ethnicy_8": "Азербайджанцы",
            "ethnicy_9": "Корейцы",
            "ethnicy_10": "Другая",
            "region_south": "Юг",
            "region_north": "Север",
            "region_west": "Запад",
            "region_east": "Восток",
            "region_center": "Центр",
            "region_other": "Другая страна",
            "occ_other": "Другой",
            "occ_student": "Студент",
            "occ_managers": "Руководители",
            "occ_professional": "Специалисты высшего уровня",
            "occ_tech": "Технические работники и специалисты среднего уровня",
            "occ_clerical": "Канцелярские/офисные работники",
            "occ_service": "Обслуживающие (сферы услуг) и торговые работники",
            "occ_skilled": "Квалифицированные аграрные, лесные, рыбопромышленные работники",
            "occ_craft": "Работники ручного/ремеслового труда и подобных занятий",
            "occ_operator": "Операторы установок и механизмов/машин, сборщики",
            "occ_unemployed": "Безработный (не наемный работник)",
            "work_9_5": "С 9 утра до 5 вечера",
            "work_flexible": "Мой график работы гибкий",
            "work_hight": "Ночные смены",
            "work_no": "Я пенсионер/безработный/студент",
            "breakfast_1": "Между 6 и 8 утра",
            "breakfast_2": "Между 8 и 10 утра",
            "breakfast_3": "Между 10 утра и полуднем",
            "breakfast_4": "Я обычно пропускаю завтрак",
            "lunch_1": "Между 10 утра и полуднем",
            "lunch_2": "Между полуднем и 2 часами дня",
            "lunch_3": "Между 2 и 4 часами дня",
            "lunch_4": "Я обычно пропускаю обед",
            "dinner_1": "Между 4 и 6 часами вечера",
            "dinner_2": "Между 6 и 8 часами вечера",
            "dinner_3": "Между 8 и 10 часами вечера",
            "dinner_4": "Я обычно пропускаю ужин",
            "activity_low": "Я в основном сижу и почти не двигаюсь",
            "activity_normal": "В основном физический активен",
            "activity_mixed": "Средне",
            "sleep_min": "Mенее 5 часов",
            "sleep_normal": "5-6 часов",
            "sleep_long": "7-8 часов",
            "sleep_2long": "Более 8 часов",
            "workout_high": "От 3 до 5 раз в неделю",
            "workout_low": "От 1 до 2 раз в неделю",
            "workout_very_low": "Менее 1 раза в неделю",
            "load_again": "Пожалуйста, загрузите изображение",
            "load_image_please": "Пожалуйста, загрузите изображение"
        },
        "kz": {
            "comment_to_image": "Экспериментке қатысуға дайынсыз. 5 күн бойы (кемінде 3 күн жұмыс күндері болуы қажет) жеген тағамдарыңыздың сүреттерін жүктеңіз.\n\n Өтініш, суретті төменде көрсетілгендей асыңызды үстінен түсіріңіз. Eгер сізде сұрақтар туындаса, келесі email-ға хабарласыңыз aifoodimage@gmail.com\n\nСуреттін сілттемесі: https://www.matain.id/article/10014/2020/1220/5-tips-skill-fotografi-untuk-maksimalkan-bisnis-kuliner-dari-food-blogger.html ",
            "hello": "Сәлеметсіз бе! ",
            "welcome": "Добро пожаловать в Бот для сбора изображений еды.",
            "thanks": "Рахмет!",
            "brief_info": 'Cізді келесі зерттеуге қатысуға шақырамыз: Жеке тамақтану іс-шараларына арналған жасанды интеллекттін (AI)  қолданысы.\n\n' 
                + 'Сипаттама: осы зерттеудің мақсаты тағамдардың түрлі суреттерің жинау болып табылады. Бұл деректер жиынтығы объектілерді анықтап жіктейтін жүйесін құрып, ' 
                + 'суреттегі тағамды анықтау үшін қолданылады.\n\nДеректер кеңінен қолданылатын платформалық жедел хабар алмасу жүйелерінің бірі Telegram арқылы жиналады. ' 
                + 'Қатысушыларға қысқа 1 минуттық сауалнаманы толтырып, бес күн ішінде тамақ суреттерін жіберу ұсынылады: 2 демалыс және 3 жұмыс күні. ' 
                + 'Эксперимент мерзімінде қатысушылар өздерімен байланысты болуы мүмкін адамдарсыз немесе заттарсыз фотосуреттер жіберу керек. ' 
                + 'Қатысушыларға күнделікті түрде ескерту жіберіледі.\n\nҚауіптер: Зерттеумен байланысты ешқандай ықтимал қауіп жоқ.\n\n' 
                + 'Пайдасы: Осы зерттеуге қатысудан қатысушыларға тікелей пайда жоқ; зерттеу нәтижелері Қазақстан халқы арасында салауатты өмір салтын ' 
                + 'насихаттау үшін тиімді тамақтану қосымшаларын/платформаларын жылжыту үшін оң әсер етуі мүмкін.\n\nӨтемақы: Ешқандай материалдық өтемақы берілмейді. ' 
                + 'Зерттеу нәтижелері зерттеу аяқталғаннан кейін мақалалар және дерек жиынтығы түрінде қол жетімді болады.\n\nҚұпиялылық: адамның жеке басын куәландыратын ақпарат жиналмайды. ' 
                + ' Барлық жиналған деректер анонимдендіріліп, Ақылды Жүйелер және Жасанды Интеллект Институтының (ISSAI) серверлерінде сақталады және оларды тек жоба зерттеушілері басқарады.' 
                + ' Мекен-жайы: Қабанбай батыр даңғылы 53, С4 блогы, 425 кеңсе.\n\nЗерттеудің ерікті сипаты. ' 
                + 'Бұл зерттеуге қатысу толықтай ерікті болып табылады және егер қатысуға келісім берілсе, экспериментке қатысу кез-келген уақытта залалсыз тоқтатылады.\n\n' 
                + 'Байланыс пункттері:\n\nБас зерттеуші: доктор Мэй-Йен Чан, yen.chan@nu.edu.kz\n\n' 
                + 'Бірлескен бас зерттеуші: доктор Хусейн Атакан Варол, ahvarol@nu.edu.kz\n\nБұл зерттеуді Назарбаев университетінің зерттеу этикасы жөніндегі комитеті қарап, тексерді. ' 
                + ' Егер сіздің қатысушы ретіндегі құқықтарыңыз туралы немесе зерттеудің қалай жүргізілетіні туралы күмәніңіз немесе сұрақтарыңыз болса, ' 
                + 'Сіз Назарбаев университетінің зерттеу этикасы жөніндегі комитетіне жүгіне аласыз. Электрондық пошта: resethics@nu.edu.kz',
            "consent": "Экспериментке қатысуға келісесіз бе? Төмендегі Мен келісемін түймесін тандау арқылы, сіз кем дегенде 18 жаста екеніңізді көрсетіп және келісімнің осы түрін оқып, түсініп және осы зерттеуге қатысуға келісіміңізді көрсетесіз.",
            "thanks_return": "Рахмет, сіз қайтып келесіз деген үміттіеміз.",
            "age": "Жасыңызды еңгізіңіз",
            "gender": "Жынысыңыз",
            "occupation": "Кәсіп түріңізді таңдаңыз\n\n Төменде берілген тізімді айналдырып, 11 варианттан тандаңыз.",
            "shift_work": "Сіздің жұмысыңыз ауысымдық па? ",
            "schedule": "Жұмыс уақытыңыз қандай?",
            "ethnicy": "Этникалық тобыңызды тандаңыз",
            "ethnicy_other": "Этникалық тобыңызды енгізіңіз",
            "region_kz": "Қай жерде тұрасыз? Аймағыңызды таңдаңыз",
            "region_outside": "Өтініш, қалаңызды еңгізіңіз ",
            "height": "Бойыңыз (см)",
            "weight": "Салмағыңыз (кг)",
            "waist_circumference": "Беліңіздің өлшемі (см), білмейтін жағдайда 0 еңгізіңіз",
            "is_smoking": "Темекі шегесіз бе?",
            "ideal_weight": "Сіздің мақсат салмағыңыз (кг)",
            "breakfast": "Сіз әдетте таңғы асты қашан ішесіз?",
            "lunch": "Сіз әдетте сағат нешеде түскі асты ішесіз?",
            "dinner": "Сіз әдетте сағат нешеде кешкі асты ішесіз?",
            "activity": "Сіз жұмыста физиқалық тұрғыдан қаншалықты белсендісіз?",
            "sleep": "Әдетте неше сағат ұйықтайсыз?",
            "workout": "Сіз қаншалықты жиі жаттығасыз?",
            "diet": "Пандемиядан кейін сіздің тамақтануыңыз өзгерді ме",
            "diet_change": "Қысқаша өзгерістерді айтып кетіңіз, өтініш",
            "yes":  "ЙӘ",
            "no": "ЖОҚ",
            "sometimes": "КЕЙДЕ",
            "a_bit": "Кішкене",
            "gender_man": "Ер",
            "gender_female": "Әйел",
            "gender_other": "Басқа",
            "ethnicy_1": "Қазақ",
            "ethnicy_2": "Орыс",
            "ethnicy_3": "Өзбек",
            "ethnicy_4": "Ұйғыр",
            "ethnicy_5": "Татар",
            "ethnicy_6": "Украин",
            "ethnicy_7": "Түрік",
            "ethnicy_8": "Әзірбайжан",
            "ethnicy_9": "Кәріс",
            "ethnicy_10": "Басқа",
            "region_south": "Оңтүстің",
            "region_north": "Солтүстік",
            "region_west": "Батыс",
            "region_east": "Шығыс",
            "region_center": "Орталық",
            "region_other": "Шет ел",
            "occ_other": "Басқа",
            "occ_student": "Студент",
            "occ_managers": "Менеджер",
            "occ_professional": "Жоғары деңгейдегі мамандар",
            "occ_tech": "Техникалық мамандар және кіші мамандар",
            "occ_clerical": "Кеңсе қолдау қызметкерлері",
            "occ_service": "Қызмет көрсету және сату саласының қызметкерлері",
            "occ_skilled": "Ауыл шаруашылығының, орман шаруашылығының, балық аулаудың, тау-кен өндіру өнеркәсібінің білікті қызметкерлері",
            "occ_craft": "Қолөнер және сабақтас кәсіптер қызметкерлері",
            "occ_operator": "Зауыттар мен станоктардың операторлары, сондай-ақ монтажшылар",
            "occ_unemployed": "Жұмыссыз (жене кәсіпкер)",
            "work_9_5": "Таңғы 9-дан кешкі 5-ке дейін",
            "work_flexible": "Менің жұмыс уақытым өзіме байланытсы",
            "work_hight": "Түнгі ауысымдар",
            "work_no": "Мен зейнеткер / жұмыссыз / студентпін",
            "breakfast_1": "Таңғы 6-дан 8-ге дейін",
            "breakfast_2": "Таңғы 8-ден 10-ға дейін",
            "breakfast_3": "Таңғы 10-дан түске дейін",
            "breakfast_4": "Мен әдетте таңғы асты өткізіп жіберемін",
            "lunch_1": "Таңертеңгі 10-дан түске дейін",
            "lunch_2": "12-ден ден 2-ге дейін",
            "lunch_3": "Күннің 2 және 4 сағаттарының арасында",
            "lunch_4": "Мен әдетте түскі асты өткізіп жіберемін",
            "dinner_1": "Кешкі сағат 4-тен 6-ға дейін",
            "dinner_2": "Кешкі сағат 6-дан 8-ге дейін",
            "dinner_3": "Кешкі 8-ден 10-ға дейін",
            "dinner_4": "Мен әдетте кешкі асты өткізіп жіберемін",
            "activity_low": "Мен негізінен отырамын және көп қозғалмаймын",
            "activity_normal": "Физикалық еңбек жасаймын және өте белсендімін",
            "activity_mixed": "Орташа",
            "sleep_min": "5 сағаттан кем",
            "sleep_normal": "5-6 сағат",
            "sleep_long": "7-8 сағат",
            "sleep_2long": "8 сағаттан астам",
            "workout_high": "Аптасына 3-5 рет",
            "workout_low": "Аптасына 1-ден 2 рет",
            "workout_very_low": "Аптасына 1 реттен кем",
            "load_again": "Қайта жүктеңіз",
            "load_image_please":  "Өтініш, сурет жүктеңіз"
        }
    }
    result = ''
    try:
        result = texts_data[lang][code]
    except:
        result = 'ERROR in TEXT RETRIEVING'

    return result
